# Stage 1: Builder
FROM node:20 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Runtime
FROM node:20-alpine AS runner

WORKDIR /app

# Copy only built output and production dependencies
COPY --from=builder /app/package*.json ./
RUN npm install --only=production

COPY --from=builder /app/app.js ./

EXPOSE 3000
CMD ["npm", "start"]
